name: smart_iot
description: "This is a project Flutter App control IoT Device "

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  flutter_svg: ^2.0.10+1
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.4
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  dartz: ^0.10.1
  cloud_firestore: ^5.4.0
  just_audio: ^0.9.42
  flutter_dotenv: ^5.2.1
  google_generative_ai: ^0.4.6
  equatable: ^2.0.7
  shared_preferences: ^2.2.3
  font_awesome_flutter: ^10.8.0
  chart_sparkline: ^1.1.1
  firebase_database: ^11.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/
    - .env
  fonts:
     - family: Satoshi
       fonts:
         - asset: assets/fonts/Satoshi-Black.ttf
           weight: 900
         - asset: assets/fonts/Satoshi-Bold.ttf
           weight: 600
         - asset: assets/fonts/Satoshi-Medium.ttf
           weight: 500
         - asset: assets/fonts/Satoshi-Regular.ttf
           weight: 400
         - asset: assets/fonts/Satoshi-Light.ttf
           weight: 300
