// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKAzdi9YtnMmqYV6Hc-KtFmcvhFZmfxak',
    appId: '1:567061341737:web:7524540b3356c3df3dde38',
    messagingSenderId: '567061341737',
    projectId: 'mike-spotify',
    authDomain: 'mike-spotify.firebaseapp.com',
    storageBucket: 'mike-spotify.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOizcI807hHxkY1xmpswJ-X2m7pNlsCJ0',
    appId: '1:567061341737:android:680f536c4146cf283dde38',
    messagingSenderId: '567061341737',
    projectId: 'mike-spotify',
    storageBucket: 'mike-spotify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnVJldPuHYBZRkgjnWkxD2EeJopFiYsYo',
    appId: '1:567061341737:ios:654cde1b3c7952763dde38',
    messagingSenderId: '567061341737',
    projectId: 'mike-spotify',
    storageBucket: 'mike-spotify.appspot.com',
    iosBundleId: 'com.miketesla.smartIot',
  );

}